import os
from typing import Annotated, Sequence
from typing_extensions import TypedDict

from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import BaseMessage, ToolMessage, AIMessage, SystemMessage
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode
from langgraph.checkpoint.memory import MemorySaver

from mcp import ClientSession
from mcp.client.streamable_http import streamablehttp_client
from rag_engine import search_sales_policies

MCP_SERVER_URL = os.getenv("MCP_SERVER_URL", "http://localhost:5000/mcp")

# Tools served by the Fineract MCP server; calls to these are routed to the mcp_executor node
MCP_TOOL_DEFINITIONS = [
    {
        "name": "get_client_loans",
        "description": (
            "Lists all loan accounts for a client by their numeric client ID: product, status, "
            "principal, amount paid, arrears and key dates. Use it when the user asks about a client's loans."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "description": "The numeric client ID, e.g., 345544"
                }
            },
            "required": ["client_id"]
        }
    },
    {
        "name": "get_loan_details",
        "description": (
            "Fetches full details of a single loan by its numeric loan ID: balances, repayment schedule, "
            "transactions and delinquency. Use it when the user wants to drill into a specific loan."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "loan_id": {
                    "type": "string",
                    "description": "The numeric loan ID (not the account number), e.g., 139"
                }
            },
            "required": ["loan_id"]
        }
    },
]
MCP_TOOL_NAMES = {t["name"] for t in MCP_TOOL_DEFINITIONS}

class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], add_messages]

@tool
def query_sales_policy_rag(query: str) -> str:
    """
    Use this tool to look up information regarding corporate sales policies, 
    return windows, warranties, exceptions, and procedural guidelines.
    """
    print(f"-> [EXECUTING RAG] Searching vector store for: {query}")
    return search_sales_policies(query)

async def execute_mcp_tool(tool_name: str, arguments: dict) -> str:
    try:
        async with streamablehttp_client(MCP_SERVER_URL) as (read, write, _):
            async with ClientSession(read, write) as session:
                await session.initialize()
                print(f"-> [EXECUTING MCP SERVER] Tool: {tool_name} with args: {arguments}")
                result = await session.call_tool(tool_name, arguments=arguments)
    except Exception as e:
        return f"Loan lookup service is unavailable: {str(e)}"

    # result.content is a list of content blocks; keep the text ones
    text = "\n".join(block.text for block in result.content if getattr(block, "type", None) == "text")
    if result.isError:
        return f"Loan lookup failed: {text or 'unknown error'}"
    return text or "Loan lookup returned no data."

tools = [query_sales_policy_rag]
tool_node = ToolNode(tools)

# Force streaming mode to true to ensure token emission works natively
model = ChatOpenAI(model="gpt-4o", temperature=0, streaming=True)

async def call_model(state: AgentState):
    messages = state["messages"]
    
    SYSTEM_GUARD_PROMPT = SystemMessage(content=(
        "You are an exclusive corporate sales policy and client loans support assistant. "
        "Your responses are strictly bounded by corporate guidelines and available internal API system resources.\n\n"
        "CRITICAL BOUNDARY RULES:\n"
        "1. You are only authorized to answer inquiries using context generated by the `query_sales_policy_rag` tool "
        "or the loan tools `get_client_loans` and `get_loan_details`.\n"
        "2. If a user asks a general-knowledge question, political query, or general topic outside company data (e.g., 'Who is Trump', history, pop culture, logic tasks), you must immediately bypass all tools.\n"
        "3. For out-of-scope requests, output exactly this message: "
        "'I am sorry, I am only authorized to assist with sales policy queries and client loan lookups. I could not find information regarding that topic in our database.'\n"
        "4. If a tool executes and returns empty results, state clearly that the specification could not be located in company manuals.\n\n"
        "LOAN LOOKUP RULES:\n"
        "- For questions about a client's loans, call `get_client_loans` with the client ID. If no client ID is given, ask for it.\n"
        "- When listing loans, give each loan's ID, product, status, principal, amount paid and key dates, "
        "and tell the user they can ask for any loan ID to see its full details.\n"
        "- For questions about one specific loan (schedule, repayments, balance, arrears), call `get_loan_details` with the loan ID.\n"
        "- Only report figures that appear in the tool output. Include the currency when the data provides one; never guess it.\n"
        "- If the tool says a client or loan was not found, or that credentials were rejected, tell the user plainly."
    ))
    
    # One tool call per turn: the router dispatches a single call to either executor node
    model_with_tools = model.bind_tools(tools + MCP_TOOL_DEFINITIONS, parallel_tool_calls=False)
    
    # Re-assemble state arrays transparently without mutating active message array configurations
    compiled_history = [SYSTEM_GUARD_PROMPT] + [m for m in messages if not isinstance(m, SystemMessage)]
    
    response = await model_with_tools.ainvoke(compiled_history)
    return {"messages": [response]}

async def execute_tools_router(state: AgentState):
    last_message = state["messages"][-1]
    
    if not isinstance(last_message, AIMessage) or not last_message.tool_calls:
        return "end"
    
    tool_call = last_message.tool_calls[0] # Target first object explicitly
    if tool_call["name"] in MCP_TOOL_NAMES:
        return "mcp_executor"
    
    return "standard_tools"

async def mcp_executor_node(state: AgentState):
    last_message = state["messages"][-1]
    tool_call = last_message.tool_calls[0]
    
    mcp_response = await execute_mcp_tool(
        tool_name=tool_call["name"], 
        arguments=tool_call["args"]
    )
    
    mcp_tool_message = ToolMessage(
        content=mcp_response,
        tool_call_id=tool_call["id"],
        name=tool_call["name"]
    )
    
    return {"messages": [mcp_tool_message]}

workflow = StateGraph(AgentState)
workflow.add_node("agent", call_model)
workflow.add_node("standard_tools", tool_node)
workflow.add_node("mcp_executor", mcp_executor_node)

workflow.add_edge(START, "agent")
workflow.add_conditional_edges(
    "agent",
    execute_tools_router,
    {
        "standard_tools": "standard_tools",
        "mcp_executor": "mcp_executor",
        "end": END
    }
)
workflow.add_edge("standard_tools", "agent")
workflow.add_edge("mcp_executor", "agent")

# In-memory conversation history keyed by thread_id (resets when the process restarts)
app = workflow.compile(checkpointer=MemorySaver())
